### ISSUE TITLE
db

### ISSUE THREAD

**Issue by RyanMesser** [firefart/rt-docker#19]
Hi,

Seeing below when the postgres db starts? 

STATEMENT:  SELECT  * FROM Users WHERE LOWER(Name) = LOWER($1)
ERROR:  relation "users" does not exist at character 16

**Comment by firefart** [comment]
Please refer to the install instructions here https://github.com/firefart/rt-docker#init-database and the official docs on what else might be needed on the database https://docs.bestpractical.com/rt/5.0.3/index.html
