### ISSUE TITLE
email

### ISSUE THREAD

**Issue by RyanMesser** [firefart/rt-docker#21]
Hi!
I might be missing something, but emails aren't sending and I get this in logs

```[/opt/rt5/sbin/../lib/RT/Interface/Web.pm:420]
[7] [Mon Oct 17 15:11:14 2022] [critical]: <rt-5.0.3-7-1666019473-159.12-7-0@example.com>: Could not send mail with command `/usr/bin/msmtp -oi -t`: <rt-5.0.3-7-1666019473-159.12-7-0@example.com>: `/usr/bin/msmtp -oi -t` exited with code 76 at /opt/rt5/sbin/../lib/RT/Interface/Email.pm line 954.
```

Config file is in place with appropriate settings for Office 365. I can send an email manually from command line within the container with sendmail -a "emailaddress" and email is recieved. 

Config file is as below with creds obscured, the from and user match.

```
account smtp
host smtp.office365.com
port 587
tls on
tls_starttls on
from test@test.com
tls_trust_file /etc/ssl/certs/ca-certificates.crt
tls_certcheck on
auth on
user test@test.com
password testpw
logfile -
```

Apologies if obvious but haven't managed to move past this yet, and is only remaining issue.

**Comment by firefart** [comment]
Hi @RyanMesser ,
you can try to set the logfile to `/dev/stderr` and see if the msmtp command gives some additional infos (there will be a permission denied error for stderr which you can ignore).

You might also need to tweak https://docs.bestpractical.com/rt/5.0.3/RT_Config.html#Sendmail-configuration (`$SendmailArguments`).

Is the file /etc/ssl/certs/ca-certificates.crt also accessible in the container? For debugging you can also try to send an email by hand in the container with `/usr/bin/msmtp -oi -t ......` and see the output

**Comment by firefart** [comment]
you can try setting `tls_starttls` to off to rule that line out and `tls_certcheck` later on to see if it fails on certificate verification.

**Comment by firefart** [comment]
There is also a `--debug` option to msmtp which you can set to see more info. You can set this in `$SendmailArguments` via https://docs.bestpractical.com/rt/5.0.3/RT_Config.html#Sendmail-configuration

**Comment by RyanMesser** [comment]
Turned off starttls but then got tls handshake failure as have to use starttls for 365. Tlscertcheck being off made no difference.

If I run in command line
echo "test" | /usr/bin/msmtp --account=smtp "test@test.com" this sends the mail fine, which would indicate to me that the settings within the mail config are fine?

Tried adding debug opition to msmtp via sendmail arguments but get the following, not sure if I've done it correctly. I still get the following error

`Oct 18 11:23:48 host=smtp.office365.com tls=on auth=on user=docker-mail@cinos.net from=docker-mail@cinos.net recipients=ryan.messer@cinos.co.uk errormsg='the server sent an invalid reply' exitcode=EX_PROTOCOL`

`[7] [Tue Oct 18 11:23:48 2022] [error]: <rt-5.0.3-7-1666092227-59.25-9-0@example.com>: `/usr/bin/msmtp --debug -t` exited with code 76 (/opt/rt5/sbin/../lib/RT/Interface/Email.pm:953)`

`[7] [Tue Oct 18 11:23:48 2022] [critical]: <rt-5.0.3-7-1666092227-59.25-9-0@example.com>: Could not send mail with command `/usr/bin/msmtp --debug -t`: <rt-5.0.3-7-1666092227-59.25-9-0@example.com>: `/usr/bin/msmtp --debug -t` exited with code 76 at /opt/rt5/sbin/../lib/RT/Interface/Email.pm line 954.`

**Comment by RyanMesser** [comment]
Just realised I get the same wether I put arguments or not

`Could not send mail with command `/usr/bin/msmtp -oi -t`: <rt-5.0.3-7-1666093221-1054.27-8-0@example.com>: `/usr/bin/msmtp -oi -t` exited with code 76 at /opt/rt5/sbin/../lib/RT/Interface/Email.pm line 954.`

**Comment by RyanMesser** [comment]
On a queue, for some reason I had an email inside the Comment Address and Reply Address fields, as soon as I remove those the emails will send. Worked this out by enabling debugging and explains why sending via CLI was fine. 

Thanks for the assistance.
