### ISSUE TITLE
LDAP support

### ISSUE THREAD

**Issue by comfreak89** [firefart/rt-docker#22]
Hi,

is there any LDAP support? If I enable the LDAP Auth Config the container tells me in the logs, that the plugin is not enabled/installed.

```
rt_1          | Can't locate Net/LDAP.pm in @INC (you may need to install the Net::LDAP module) (@INC contains: /opt/rt5/sbin/../local/lib /opt/rt5/local/plugins/RT-Extension-MergeUsers/lib /opt/rt5/local/plugins/RT-Extension-TerminalTheme/lib /opt/rt5/sbin/../lib /usr/local/lib/perl5/site_perl/5.36.0/x86_64-linux-gnu /usr/local/lib/perl5/site_perl/5.36.0 /usr/local/lib/perl5/5.36.0/x86_64-linux-gnu /usr/local/lib/perl5/5.36.0) at /opt/rt5/sbin/../lib/RT/Authen/ExternalAuth/LDAP.pm line 51.
``` 
https://docs.bestpractical.com/rt/5.0.0/RT/Authen/ExternalAuth/LDAP.html

Maybe only `RUN cpan -i RT::Authen::ExternalAuth` has to be added to the Dockerfile?

**Comment by firefart** [comment]
Tried to add it here https://github.com/firefart/rt-docker/commit/e2c414ae48ab6d5caecd43c5447925d40fd5f597 let's see if it builds and if that is enough to enable LDAP

**Comment by firefart** [comment]
@comfreak89 build was successful, can you please try with the latest image?

**Comment by comfreak89** [comment]
At first glance it seems to work!
