### ISSUE TITLE
Issue with retrieve some emails coming from Outlook

### ISSUE THREAD

**Issue by comfreak89** [firefart/rt-docker#24]
Hi,

sometimes RT can not retreive emails sent to our support address, when they are coming from Outlook. They will not show up in RT and no notification is generated to the watchers/admin of the queue.

I activated the debug log: [https://pastebin.com/s0yA3aVm](https://pastebin.com/s0yA3aVm)

It is reproduceable for example with my personal email account when sending out of Outlook. We have an web interface on our email server ([Kopano](https://kopano.com/)) and when sending with my email address from that, the issue does not occure. The log says something about attachment, but I did not send any attachment with it.

More curious: If I setup my email postbox in an Outlook of one of my colleagues (same Version: Outlook 2013, 15.0.5501.1000), it works! So, It thought my Outlook is buggy, and reinstalled my Outlook (uninstall + MS removal tool), but the issue is still there.

I thought that maybe only my "email+Outlook" combination is affected, however as it turns out, we had the same issue with an other colleague yesterday. Probably more colleages are affected so I disabled the IMAP retrieve functionallity and put in a rule just to forward the emails sent to our support email to us watchers/admins of the queue

getmailrc config:

```
[retriever]
#type = SimpleIMAPSSLRetriever
type = SimpleIMAPRetriever
server = 192.168.xxx.yy
username = <username>
password = <password>
mailboxes = ("INBOX",)

[destination]
type = MDA_external
path = /opt/rt5/bin/rt-mailgate
user = rt
group = rt
# 8080 is the mailgate vhost
arguments = ("--url", "http://nginx:8080/", "--queue", "Allgemein", "--action", "correspond",)

[options]
read_all = false
delete = true
verbose = 1
```

Any idea?

Thanks!

**Comment by firefart** [comment]
Hi,
this looks like bug in rt itself as it generates invalid insert statements. Getting support from them is pretty hard but you can try over here: https://rt.bestpractical.com/

I think this has nothing to do with the docker setup, sorry.
