### ISSUE TITLE
app-wsgetmail in docker image

### ISSUE THREAD

**Issue by LukaszWasko** [firefart/rt-docker#36]
Could you please install the [app-wsagetmail](https://github.com/bestpractical/app-wsgetmail) in the docker image for communication with o365 mailboxes using OAuth2?
app-wsgetmail [is recommended ](https://bestpractical.com/blog/2022/1/new-microsoft-office-365-email-integration-option-for-rt)for this very purpose.

**Comment by firefart** [comment]
Thanks, I've added it to the dockerfile. The images are currently rebuilding so it will be available in around one hour on dockerhub

**Comment by firefart** [comment]
Images are now available on dockerhub: https://hub.docker.com/repository/docker/firefart/requesttracker/general
