### ISSUE TITLE
rt-fulltext-indexer error

### ISSUE THREAD

**Issue by rizlas** [firefart/rt-docker#37]
Hi,
I just upgraded my dev environment to 5.0.5 from 5.0.4.

After the update rt-fulltext-indexer command is triggering this error:

`Attempt to call undefined import method with arguments ("1.40") via package "DBIx::SearchBuilder" (Perhaps you forgot to load the package?) at /opt/rt5/sbin/../lib/RT/SearchBuilder.pm line 75.`

Same error popped up after upgrade command:

`perl ./sbin/rt-setup-database --action upgrade --upgrade-from 5.0.4`

I'm currently failing to find some infos from official request tracker forum.

Anyone here issuing the same error?

Thank you

Edit: without this line https://github.com/bestpractical/rt/blob/stable/lib/RT/SearchBuilder.pm#L75 no errors are shown. Idk perl, so really don't know what is happening. For sure something is wrong with the version stated in SearchBuilder.pm (https://github.com/bestpractical/rt/blob/stable/etc/cpanfile#L25)

**Comment by firefart** [comment]
Hi, yes this happens since the latest Perl upgrade but haven’t got an update on the bug tracker on this one yet (https://rt.bestpractical.com/Ticket/Display.html?id=37702)
Haven’t had any issues so far so it looks like it is still working despite the message. I ended up grepping away the status message inside the cron job to not trigger any error emails

**Comment by rizlas** [comment]
Thank you

**Comment by firefart** [comment]
Here's my current crontab for reference:

```text
# clean shorteners
0 0 * * * rt /opt/rt5/sbin/rt-clean-shorteners 2>&1 | grep -v "Attempt to call undefined import method with arguments"

# refresh full text index
0 * * * * rt /opt/rt5/sbin/rt-fulltext-indexer --quiet 2>&1 | grep -v "Attempt to call undefined import method with arguments" 

# email dashboards
0 * * * * rt /opt/rt5/sbin/rt-email-dashboards 2>&1 | grep -v "Attempt to call undefined import method with arguments"

# send reminders
# https://docs.bestpractical.com/rt/5.0.3/reminders.html
0 23 * * * rt /opt/rt5/bin/rt-crontool --search RT::Search::FromSQL --search-arg 'Type = "reminder" and (Status = "open" or Status = "new")' --condition RT::Condition::BeforeDue --condition-arg 1d --action RT::Action::Notify --action-arg Owner,AlwaysNotifyActor --transaction first --template 'Reminder' 2>&1 | grep -v "Attempt to call undefined import method with arguments"
```

**Comment by rizlas** [comment]
Thank you, that help a lot.
So the problem is spread beyond the indexing command.

Dunno why best practical disabled github issues. I googled the error message. Because of the authentication used by their bugtracker your ticket is not showed 😕

**Comment by firefart** [comment]
I think they disabled it because the github repo seems just to be a clone of their internal svn. There is also almost no way to reach out to them to report bugs because the issue tracker is full of spam.
So we need to hope they encounter it themselves and fix it in the next release 🤷🏻‍♂️

**Comment by rizlas** [comment]
Oh I see. I've also an open PR with them since 6 month (https://github.com/bestpractical/rt/pull/365). No answers from them.

Yeah let's hope. 🙏
