### ISSUE TITLE
RTIR 

### ISSUE THREAD

**Issue by TheGuardianLight** [firefart/rt-docker#49]
Hi there!

I'd like to add some elements to customise RTIR in the /html/RTIR/Tools/Elements/ folder, but it turns out that it doesn't exist in /opt/rt5 or /opt/rtir ...

Could you help me define where I should put it ???

**Comment by TheGuardianLight** [comment]
![image](https://github.com/firefart/rt-docker/assets/64707127/e3cf025e-adec-4a52-8cfa-9b26d20bd04c)

**Comment by firefart** [comment]
It's inside `/opt/rt5/local/plugins/RT-IR/html/RTIR`. If you want to modify the contents I would suggest creating a new image with this repo as a base image and putting in your custom files.
