### ISSUE TITLE
Change nginx port number via startup-scripts?

### ISSUE THREAD

**Issue by Lx** [FireFart/rt-docker#9]
I'm trying to change the nginx port number from 443 to e.g. 4433 to avoid clashing with the reverse proxy already running on the host.

Based on the instructions and example startup script given in the README, I thought I could get away with adding this content to a new file in `nginx/startup-scripts`:

```sh
#!/bin/sh

set -e

echo "chanigng port number"
sed -i 's/443/4433/' /etc/nginx/conf.d/default.conf
echo "finished"
```

but it doesn't seem to be doing anything, and I get these errors when I try to fire up the containers:

```
Creating rt_nginx_1 ... error

ERROR: for rt_nginx_1  Cannot start service nginx: driver failed programming external connectivity on endpoint rt_nginx_1 (1165b998b7f1adcc4546bfc7c59baa9844d4eb10cf094200e233efc64db0ff51): Error starting userland proxy: listen tcp4 0.0.0.0:443: bind: address already in use

ERROR: for nginx  Cannot start service nginx: driver failed programming external connectivity on endpoint rt_nginx_1 (1165b998b7f1adcc4546bfc7c59baa9844d4eb10cf094200e233efc64db0ff51): Error starting userland proxy: listen tcp4 0.0.0.0:443: bind: address already in use
```

I've set `chmod +x` on the script too.  Are there any obvious errors in the above?

**Comment by FireFart** [comment]
Changing the port number in nginx alone won't work as the port is exposed via docker-compose. If you want to change the port on the host, simply change it in docker-compose and leave nginx on default

**Comment by Lx** [comment]
Oh lord, what a rookie mistake.  Thank you, and sorry.
